/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2010-11-3: 14h:28m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/array.cats"
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologue from statically loaded files */
/* external codes at top */
/* type definitions */
typedef struct {
ats_ptr_type atslab_prev ;
ats_ptr_type atslab_next ;
ats_int_type atslab_itm ;
} anairiats_rec_0 ;

/* external typedefs */
/* external dynamic constructor declarations */
/* external dynamic constant declarations */
extern
ats_void_type atspre_assert_errmsg (ats_bool_type, ats_ptr_type) ;
extern
ats_bool_type atspre_neg_bool1 (ats_bool_type) ;
ATSextern_val(ats_ptr_type, atspre_null_ptr) ;
extern
ats_bool_type atspre_peq (ats_ptr_type, ats_ptr_type) ;
extern
ats_size_type atspre_add_size1_int1 (ats_size_type, ats_int_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type _2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2esats__dlseg_v_append_prfck () ;
extern
ats_void_type _2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2esats__dlseg_v_1_append_prfck () ;
extern
ats_void_type _2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2esats__dlseg_v_1_of_dlseg_v_prfck () ;
extern
ats_void_type _2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2esats__dlseg_v_of_dlseg_v_1_prfck () ;
extern
ats_void_type _2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2esats__dllst_v_of_zipper_v_prfck () ;
extern
ats_void_type _2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2esats__dllst_v_1_of_zipper_v_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_void_type dllst_make_empty_01559__ats_int_type (ats_ref_type arg0, ats_ref_type arg1) ;
static
ats_void_type dllst_cons_01564__ats_int_type (ats_ref_type arg0, ats_ref_type arg1, ats_ptr_type arg2) ;
static
ats_void_type dllst_uncons_01565__ats_int_type (ats_ref_type arg0, ats_ref_type arg1, ats_ref_type arg2) ;

/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/artyom/proj/my-ats-contrib/dlseg/dlseg.dats: 1999(line=69, offs=31) -- 2072(line=73, offs=4)
*/
ats_void_type
dllst_make_empty_01559__ats_int_type (ats_ref_type arg0, ats_ref_type arg1) {
/* local vardec */
ATSlocal_void (tmp7) ;

__ats_lab_dllst_make_empty_01559__ats_int_type:
*((ats_ptr_type*)arg0) = atspre_null_ptr ;
*((ats_ptr_type*)arg1) = atspre_null_ptr ;
return /* (tmp7) */ ;
} /* end of [dllst_make_empty_01559__ats_int_type] */

/*
// /home/artyom/proj/my-ats-contrib/dlseg/dlseg.dats: 3299(line=119, offs=38) -- 3701(line=136, offs=6)
*/
ats_void_type
dllst_cons_01564__ats_int_type (ats_ref_type arg0, ats_ref_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal_void (tmp10) ;
ATSlocal (ats_bool_type, tmp11) ;

__ats_lab_dllst_cons_01564__ats_int_type:
tmp11 = atspre_peq (*((ats_ptr_type*)arg0), atspre_null_ptr) ;
if (tmp11) {
((anairiats_rec_0*)arg2)->atslab_next = atspre_null_ptr ;
((anairiats_rec_0*)arg2)->atslab_prev = atspre_null_ptr ;
*((ats_ptr_type*)arg0) = arg2 ;
*((ats_ptr_type*)arg1) = arg2 ;
} else {
((anairiats_rec_0*)arg2)->atslab_next = *((ats_ptr_type*)arg0) ;
((anairiats_rec_0*)arg2)->atslab_prev = atspre_null_ptr ;
((anairiats_rec_0*)*((ats_ptr_type*)arg0))->atslab_prev = arg2 ;
*((ats_ptr_type*)arg0) = arg2 ;
} /* end of [if] */
return /* (tmp10) */ ;
} /* end of [dllst_cons_01564__ats_int_type] */

/*
// /home/artyom/proj/my-ats-contrib/dlseg/dlseg.dats: 3740(line=138, offs=38) -- 4191(line=157, offs=6)
*/
ats_void_type
dllst_uncons_01565__ats_int_type (ats_ref_type arg0, ats_ref_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal_void (tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_ptr_type, tmp23) ;
ATSlocal (ats_bool_type, tmp24) ;

__ats_lab_dllst_uncons_01565__ats_int_type:
tmp22 = *((ats_ptr_type*)arg0) ;
tmp23 = ((anairiats_rec_0*)*((ats_ptr_type*)arg0))->atslab_next ;
tmp24 = atspre_peq (tmp23, atspre_null_ptr) ;
if (tmp24) {
*((ats_ptr_type*)arg0) = atspre_null_ptr ;
*((ats_ptr_type*)arg1) = atspre_null_ptr ;
*((ats_ptr_type*)arg2) = tmp22 ;
} else {
((anairiats_rec_0*)tmp23)->atslab_prev = atspre_null_ptr ;
*((ats_ptr_type*)arg2) = *((ats_ptr_type*)arg0) ;
*((ats_ptr_type*)arg0) = tmp23 ;
} /* end of [if] */
return /* (tmp21) */ ;
} /* end of [dllst_uncons_01565__ats_int_type] */

/*
// /home/artyom/proj/my-ats-contrib/dlseg/dlseg_test.dats: 443(line=18, offs=16) -- 1378(line=46, offs=4)
*/
ats_void_type
mainats (ats_int_type arg0, ats_ref_type arg1) {
/* local vardec */
ATSlocal_void (tmp0) ;
ATSlocal (anairiats_rec_0, tmp1) ;
ATSlocal (anairiats_rec_0, tmp2) ;
ATSlocal (anairiats_rec_0, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal_void (tmp6) ;
ATSlocal_void (tmp8) ;
ATSlocal_void (tmp9) ;
ATSlocal_void (tmp12) ;
ATSlocal_void (tmp13) ;
ATSlocal_void (tmp14) ;
ATSlocal_void (tmp15) ;
ATSlocal_void (tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_ptr_type, tmp19) ;
ATSlocal_void (tmp20) ;
ATSlocal_void (tmp25) ;
ATSlocal_void (tmp26) ;
ATSlocal_void (tmp27) ;
ATSlocal_void (tmp28) ;
ATSlocal_void (tmp29) ;
ATSlocal_void (tmp30) ;
ATSlocal (ats_bool_type, tmp31) ;
ATSlocal (ats_bool_type, tmp32) ;

__ats_lab_mainats:
/* anairiats_rec_0 tmp1 ; */
tmp1.atslab_prev = atspre_null_ptr ;
tmp1.atslab_next = atspre_null_ptr ;
tmp1.atslab_itm = 5 ;

/* anairiats_rec_0 tmp2 ; */
tmp2.atslab_prev = atspre_null_ptr ;
tmp2.atslab_next = atspre_null_ptr ;
tmp2.atslab_itm = 10 ;

/* anairiats_rec_0 tmp3 ; */
tmp3.atslab_prev = atspre_null_ptr ;
tmp3.atslab_next = atspre_null_ptr ;
tmp3.atslab_itm = 15 ;

/* ats_ptr_type tmp4 ; */
/* ats_ptr_type tmp5 ; */
/* tmp6 = */ dllst_make_empty_01559__ats_int_type ((&tmp4), (&tmp5)) ;
/* tmp8 = (tmp6) */ ;
/* tmp9 = */ dllst_cons_01564__ats_int_type ((&tmp4), (&tmp5), (&tmp1)) ;
/* tmp12 = (tmp9) */ ;
/* tmp13 = */ dllst_cons_01564__ats_int_type ((&tmp4), (&tmp5), (&tmp2)) ;
/* tmp14 = (tmp13) */ ;
/* tmp15 = */ dllst_cons_01564__ats_int_type ((&tmp4), (&tmp5), (&tmp3)) ;
/* tmp16 = (tmp15) */ ;
/* ats_ptr_type tmp17 ; */
/* ats_ptr_type tmp18 ; */
/* ats_ptr_type tmp19 ; */
/* tmp20 = */ dllst_uncons_01565__ats_int_type ((&tmp4), (&tmp5), (&tmp19)) ;
/* tmp25 = (tmp20) */ ;
/* tmp26 = */ dllst_uncons_01565__ats_int_type ((&tmp4), (&tmp5), (&tmp18)) ;
/* tmp27 = (tmp26) */ ;
/* tmp28 = */ dllst_uncons_01565__ats_int_type ((&tmp4), (&tmp5), (&tmp17)) ;
/* tmp29 = (tmp28) */ ;
tmp31 = atspre_peq (tmp18, (&tmp2)) ;
/* tmp30 = */ atspre_assert_errmsg (tmp31, (ats_ptr_type)"something bad happened") ;
tmp32 = atspre_peq (tmp17, (&tmp1)) ;
/* tmp0 = */ atspre_assert_errmsg (tmp32, (ats_ptr_type)"something bad happened") ;
return /* (tmp0) */ ;
} /* end of [mainats] */

/* static load function */

// extern ats_void_type _2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2esats__staload (void) ;
// extern ats_void_type _2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2edats__staload (void) ;
static int _2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_test_2edats__staload_flag = 0 ;

ats_void_type
_2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_test_2edats__staload () {
if (_2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_test_2edats__staload_flag) return ;
_2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_test_2edats__staload_flag = 1 ;
// _2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2esats__staload () ;
// _2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2edats__staload () ;
return ;
} /* staload function */
/* dynamic load function */

// (external) dynload flag declaration
// extern
// int _2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_test_2edats__dynload_flag ;

ats_void_type
_2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_test_2edats__dynload () {
// _2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_test_2edats__dynload_flag = 1 ;
_2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_test_2edats__staload () ;
#ifdef _ATS_PROOFCHECK
_2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2esats__dlseg_v_append_prfck () ;
_2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2esats__dlseg_v_1_append_prfck () ;
_2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2esats__dlseg_v_1_of_dlseg_v_prfck () ;
_2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2esats__dlseg_v_of_dlseg_v_1_prfck () ;
_2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2esats__dllst_v_of_zipper_v_prfck () ;
_2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_2esats__dllst_v_1_of_zipper_v_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

int main (int argc, char *argv[]) {
ATS_GC_INIT() ;
mainats_prelude() ;
_2home_2artyom_2proj_2my_2dats_2dcontrib_2dlseg_2dlseg_test_2edats__dynload() ;
mainats((ats_int_type)argc, (ats_ptr_type)argv) ;
return (0) ;
} /* end of main */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [dlseg_test_dats.c] */
